config_env_task:
  description: >
    Your task is to configure the environment dynamically.
    With help from your Dynamic Environment Key tool, you only need to use the tool and return the project id configured. 
  expected_output: >
    A expected output should be a project id configured correctly.

research_task:
  description: >
    Your task is to analyze and identify the root cause of the firebase error. 
    With help from your BigQuery tool, you only need to provide the 
    error message and the relevant code snippet. 
  expected_output: >
    A expected output should be a report documenting the root cause of the firebase error

git_repo_task:
  description: >
    Your task is to manage Git operations for a specific project. 
    Begin by cloning the repository with tool. 

    Instructions
    ------------
    1. Clone the repository
    2. Save repository to a folder with a tool
  expected_output: >
    A cloned repository should be saved in a folder with a tool.


git_file_task:
  description: >
    Your task is to manage Git operations for a specific project. 
    With a repository cloned, list all files in the repository and 
    locate the ones previously identified by the Senior Software Researcher as containing errors. 
    Open and confirm the contents of these files, 
    preparing them for further analysis by subsequent agents in our workflow.

    -----------------------
    Use Senior Data Researcher notes


    Instructions
    ------------
    1. Locate and list the necessary files.
    2. Your Final answer must be the entire code kotlin file, only the full kotlin code and nothing else. 
  expected_output: >
    A entire reported code error kotlin file.

identify_task:
  description: >
    You will receive some 'stacktraces' of a reported errors, 
    and will analyze and identify possible Kotlin solutions for the error, these are the instructions:

    --------------
    Error Reported
    --------------
    Use Senior Data Researcher notes

    Your final answer should be a full analyze about the reported errors, 
    just a full analyze about the reported errors and nothing else.
  expected_output: >
    Analyze of the reported error in bullet point format, 
    just the analyze of the reported error and nothing else.

suggest_task:
  description: >
    You will receive some 'stacktraces' of a reported errors, 
    and will suggest a possible Kotlin solutions for the errors, these are the instructions:

    Base Instructions
        
    --------------
    - Use Senior Data Researcher notes to understand the error reported
    - Use Git Master Enginner Notes to understand the code and the context of the error
    - Use Senior Software Analyst Notes for better understanding causes of the error
    -------------
    
    Base Instructions

    Your final answer should be code suggestions in Kotlin as well as your explanations in comment format, 
    just code suggestions in Kotlin as well as your explanations in comment format and nothing else.
    All your comments explanations should be clear, concise and in brazilian portuguese. 
  expected_output: >
    Code suggestions to solve error, with explanations how you got to the suggested code.

code_task:
  description: >
    As a senior Kotlin developer, you are tasked with implementing a solution for a reported bug. You will be provided with code and analysis from various team experts. Your goal is to implement the best solution to resolve the error using Kotlin.

    Instructions:
    ------------
    ATTENTION:
    - Do not change the type of the objects
    - If changing the type is absolutely necessary, create a comment above the line explaining why it's needed
    ------------

    1. Review the provided information:
       - Senior Data Researcher's notes on the reported error
       - Git Master Engineer's notes on the code context 
       - Software Analyst's notes on the error causes

    2. Implement the solution following these guidelines:
       - Strictly adhere to the type preservation rule mentioned above
       - Ensure the solution follows Kotlin best practices and coding standards

    3. Code Modification Rules:
       - Modify existing code as needed to fix the bug, but preserve object types
       - Ensure any new additions integrate well with the existing codebase

    4. Documentation:
       - Add clear and concise comments in Brazilian Portuguese
       - Comments should explain complex logic, important changes, and the reasoning behind your solutions
       - If a type change was unavoidable, provide a detailed explanation in the comment

    5. Final Deliverable:
       - Provide the complete, corrected Kotlin code file
       - Include only the full Kotlin code in your final answer, no additional explanations outside the code

  expected_output: >
    The complete Kotlin code file that includes:
    - The entire codebase with the implemented solution
    - Necessary comments in Brazilian Portuguese explaining key changes and complex logic
    - Any required new functions, classes, or variables to support the bug fix
    - Comments explaining any unavoidable type changes (if any)
    - No text outside of the full Kotlin code and comments

review_task:
  description: >
    You are helping to implement code to resolve the reported error using Kotlin, these are the instructions::

    Instructions
    ------------
    - Use Senior Data Researcher notes to understand the error reported
    - Use Senior Software Enginner code to analyze the solution  
    ------------

    Using the code you got, check for errors. Check for logic errors,
    syntax errors, missing imports, variable declarations, mismatched brackets,
    and security vulnerabilities.

    Your Final answer must be the full kotlin code, only the kotlin code and nothing else.
    All your comments explanations should be clear, concise and in brazilian portuguese.
  expected_output: >
    Full code kotlin file with the bug solved and 
    comments of it explanations in bullet point format 
    at the start of kotlin file.

evaluate_task:
  description: >
    You are helping to implement code to resolve the reported error using Kotlin, these are the instructions::

    Instructions
    ------------
    - Use Senior Data Researcher notes to understand the error reported
    - Use Senior Software Enginner code to analyze the solution  
    - Use Software Quality Control Enginner notes to evaluate the code
    ------------

    You will look over the code to insure that it is complete and
    does the job that it is supposed to do.

    All your comments explanations should be clear, concise and in brazilian portuguese.
    If doesn't have anything to change in the Suggested Code, so your final answer is the full Suggest Code.
    Your Final answer must be the full kotlin code, only the kotlin code and nothing else.
  expected_output: >
    Full code kotlin file with the bug solved and 
    comments of it explanations in bullet point format at 
    the start of kotlin file.
  
microsoft_teams_task:
  description: >
    Your task is to send a notification to the microsoft teams channel. 
    You will send the summary about it: The error and it solution idea.

    Your final answer should be the message sent to the microsoft teams channel.
  expected_output: >
    Full code kotlin file with the bug solved and 
    comments of it explanations in bullet point format at 
    the start of kotlin file.

